### PR TITLE
Create Ip-finder.py

### PR DESCRIPTION
**Pull request by rahulshivan05**
This code really help you find the info about the given IP address.

### CODE REVIEW

**Comment by devnarayanp02** [comment]
Thankyou, i will try, i am beginner.

**Comment by rahulshivan05** [comment]
@devnarayanp02 me too

**Comment by rahulshivan05** [comment]
But in Hacktoberfest, dashboard show's the **Project not participating**.

**Comment by devnarayanp02** [comment]
Beginner hu bhai, hacktoberfest t-shirt ke liye repo bana liya, mere me bhi
not participating aa raha hai, koi or repo dekh le. 😊

**Comment by rahulshivan05** [comment]
@devnarayanp02 koi baat nahi **Hacktoberfest ka Tag hata do**. Best of luck for Hacktoberfest t-shirt.

**Pull request merged**
